package base

var Fields = map[string]string{
	"cnpjBasico":              "",
	"cnpjOrdem":               "",
	"cnpjDV":                  "",
	"identificador":           "",
	"nomeFantasia":            "",
	"situacaoCadastral":       "",
	"dataSituacaoCadastral":   "",
	"motivoSituacaoCadastral": "",
	"nomeCidadeExterior":      "",
	"pais":                    "",
	"dataInicio":              "",
	"cnaePrincipal":           "",
	"cnaeSecundario":          "",
	"tipoLogradouro":          "",
	"logradouro":              "",
	"numero":                  "",
	"complemento":             "",
	"bairro":                  "",
	"cep":                     "",
	"uf":                      "",
	"municipio":               "",
	"ddd1":                    "",
	"telefone1":               "",
	"ddd2":                    "",
	"telefone2":               "",
	"dddFax":                  "",
	"fax":                     "",
	"email":                   "",
	"situacaoEspecial":        "",
	"dataSituacaoEspecial":    "",
	"hash":                    "",
}