create table dados (
	id serial primary key,
	cnpj varchar(16) unique,
	cnpj_basico varchar(8),
	cnpj_ordem varchar(4),
	cnpj_dv varchar(2),
	identificador varchar(2),
	nome_fantasia varchar(250),
	situacao_cadastral varchar(2),
    data_situacao_cadastral date,
	motivo_situacao_cadastral varchar(2),
	nome_cidade_exterior varchar(250),
	pais varchar(100),
	data_inicio date,
	cnae_principal varchar(7),
	cnae_secundario varchar(250),
	tipo_logradouro varchar(25),
	logradouro varchar(250),
	numero varchar(8),
	complemento varchar(100),
	bairro varchar(100),
	cep varchar(8),
	uf varchar(2),
	municipio varchar(100),
	ddd_1 varchar(3),
	telefone_1 varchar(9),
	ddd_2 varchar(3),
	telefone_2 varchar(9),
	ddd_fax varchar(3),
	fax varchar(9),
	email varchar(100),
	situacao_especial varchar(250),
	data_situacao_especial date,
	create_at timestamp,
	update_at timestamp
)